---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testservice
  template:
    metadata:
      labels:
        app: testservice
    spec:
      containers:
      - name: testservice
        image: eugenetaranov/testservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: NAME
          value: testservice

---
apiVersion: v1
kind: Service
metadata:
  name: testservice
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: testservice